### PR TITLE
Patch floor to make it retain your time zone

### PR DESCRIPTION
**Pull request by achesnais**
I found it a bit annoying that floor doesn't retain the time zone you're working with on your date.

### CODE REVIEW

**Comment by michaelklishin** [comment]
Would you please add a test that demonstrates what the problem was?

**Comment by achesnais** [comment]
Sorry, kind of new to this...

* Original floor:
    (floor (to-time-zone (date-time 2015 11 11 23) (time-zone-for-id "Africa/Johannesburg")) day)
    => #object[org.joda.time.DateTime 0xe40c74d "2015-11-12T00:00:00.000Z"]

*New floor:
    (floor (to-time-zone (date-time 2015 11 11 23) (time-zone-for-id "Africa/Johannesburg")) day)
    => #object[org.joda.time.DateTime 0x3bceac18 "2015-11-12T00:00:00.000+02:00"]

**Comment by seancorfield** [comment]
I'd recommend having several tests: some using a positive tz and some having a negative tz (e.g., Los Angeles and times of 3am and 8pm, Johannesburg and times of 1am and 11pm).

**Comment by seancorfield** [comment]
Also, Michael's comment was requesting that your PR be updated to include actual executable tests - as part of the existing test suite.

**Comment by achesnais** [comment]
Oh okay! Thanks for clarifying!

**Comment by seancorfield** [comment]
@achesnais This PR now has conflicts compared to master -- do you want to update it so it will apply cleanly, and also add in tests per the discussion back in January?

**Comment by achesnais** [comment]
Hi @seancorfield – sorry I never got a chance to take this further. I'm happy to handle if this is still relevant 👍

**Comment by seancorfield** [comment]
Yup, there's still interest.

**Comment by achesnais** [comment]
@seancorfield here you go! I've added a couple tests based on your input. Is it enough?

**Comment by seancorfield** [comment]
:+1:

**Comment by hjbolide** [comment]
Sorry to raise this super old thread, `floor` would produce incorrect result whenever DST is involved, for example:

```
(def tz-lord-howe (t/time-zone-for-id "Australia/Lord_Howe"))
(def ts #clj-time/date-time "2025-04-05T14:30:00Z")
(t/floor (t/to-time-zone ts tz-lord-howe)
         t/minute)
=> #clj-time/date-time "2025-04-05T15:00:00.000Z"
```

The moment a new date-time object is created, the original instant information would've been lost.

So I think the solution is to operate on the original instant by subtracting the portions that's finer than `dt-fn` from the original date-time object.

Thoughts?

**Comment by seancorfield** [comment]
@hjbolide This project has been deprecated for a long time, and no further changes will be made (except _perhaps_ critical security bugs). Per the README, I recommend migrating to a different time library, or using Java Time directly via interop (which is what we did at work some years back).

**Comment by hjbolide** [comment]
> @hjbolide This project has been deprecated for a long time, and no further changes will be made (except _perhaps_ critical security bugs). Per the README, I recommend migrating to a different time library, or using Java Time directly via interop (which is what we did at work some years back).

Hi Sean thanks for getting back to me, our projects have been using clj-time and only just got around to slowly migrating to Java time recently, found this issue out of whack today, so thought to raise it :). Will fix it in our own clone and not raising a merge request.

**Pull request merged**
