### PR TITLE
Update dependencies

### LINKED ISSUE #261: Dependencies out of date

### PR DESCRIPTION
**Pull request by taha-husain**
This PR updates following dependencies in project.clj
- **clojure** (1.9.0 -> **1.10.0**)
- **java.jdbc** (0.7.8 -> **0.7.9**)
- **codox** (0.10.5 -> **0.10.6**)
- **midje** (1.9.3 -> **1.9.8**)

Resolves #261

### CODE REVIEW

**Comment by seancorfield** [comment]
Why did you remove `:master`? There are 1.11.0 snapshot builds available already. It seems this PR also causes the 1.9 test to not use spec -- which is useful for the Java 7 tests.

I'm going to decline the PR, but this is a good "nudge" to go ahead and update dependencies anyway so I'll do that straight away.

**Comment by taha-husain** [comment]
@seancorfield Thank you for pointing that out. I learned something today. 🙏

**Comment by seancorfield** [comment]
Updated `project.clj` pushed to master. Tests against Clojure master (1.11.0), 1.10 with and without spec, 1.9 with spec, 1.8, 1.7.

**Comment by taha-husain** [comment]
Awesome. Thanks  🎉

**Pull request closed without merging**
