### PR TITLE
On travis Add .m2 dir in cache

### PR DESCRIPTION
**Pull request by firesofmay**
Add .m2 directory in cache on travis.
This will result in builds running faster.

### CODE REVIEW

**Comment by seancorfield** [comment]
I didn't even know you could do that. It would improve a number of other projects I run on Travis. Are there limits on what can be cached?

**Comment by michaelklishin** [comment]
@seancorfield take a look [at the docs](https://docs.travis-ci.com/user/caching/) ;)

**Comment by firesofmay** [comment]
@seancorfield Don't see any limit mentioned in the docs - https://docs.travis-ci.com/user/caching/

**Comment by seancorfield** [comment]
Documentation? Oh you two are such comedians :) :) :)

**Pull request merged**
