### PR TITLE
make do-at nesteable

### PR DESCRIPTION
**Pull request by tamasjung**

### CODE REVIEW

**Comment by michaelklishin** [comment]
What's the use case for this?

**Comment by tamasjung** [comment]
Well, if they want to use today-at function for a certain day, like (do-at another-day (today-at-midnight tz)) in application code and they want to write test for this, for instance. Anyway, with this PR it is the less surprising, that should be enough reason, IMO. Let's view it from the other direction, if we compare the old and the new do-at, what is the use-case when the old one is better?

**Comment by michaelklishin** [comment]
Sorry, "prove that the old version is better" is not an argument I'd buy. The old one does not have shared state beyond what's unavoidable (setting Joda Time internal clock).

I hardly can think of a realistic use case for this beyond test environments, which can fairly easily implement their own helper.

**Comment by seancorfield** [comment]
Re: test environments -- Expectations, for one, has a feature to "freeze time" for exactly this reason. It seems to me this feature belongs in the test libraries, not clj-time.

**Comment by russellwhitaker** [comment]
That is a perfectly awesome feature of Expectations, Sean! I've been using
Speclj for my own testing, but if I need
this:

http://jayfields.com/expectations/freeze-time.html

...I'll consider it myself.

ObTopicalComment: baking testing concerns into production code is generally
an antipattern.

Russell

On Tue, Mar 24, 2015 at 4:15 PM, Sean Corfield <notifications@github.com>
wrote:

> Re: test environments -- Expectations, for one, has a feature to "freeze
> time" for exactly this reason. It seems to me this feature belongs in the
> test libraries, not clj-time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clj-time/clj-time/pull/173#issuecomment-85735680>.
>



-- 
Russell Whitaker
http://twitter.com/OrthoNormalRuss
http://www.linkedin.com/pub/russell-whitaker/0/b86/329

**Comment by tamasjung** [comment]
@michaelklishin You wrote too that the only disadvantage is unavoidable, Joda already uses a state, a fake time provider, this PR would not make this fact worse only better.

Moving the macro to another lib or ns is a different question, a much bigger pain, I would not have dared to suggest it ...

**Comment by michaelklishin** [comment]
@tamasjung yeah, now you are twisting my words. This is not going to be merged.

**Pull request closed without merging**
