### PR TITLE
Adding 'number-of-weeks-in-the-year -> joda WeekOfWeekyear

### PR DESCRIPTION
**Pull request by adomokos**
The great joda library has a property called WeekOfWeekyear,
the number-of-weeks-in-the-year function exposes that.

### CODE REVIEW

**Comment by seancorfield** [comment]
It's a poor name for the function. The "number of weeks in [a] year" is always 52. I think it should be `week-of-year` or `week-number-of-year` (I have no preference and would like others to suggest names). I think Joda's `WeekOfWeekyear` is also a poor name since `Weekyear` doesn't mean anything obvious.

**Comment by adomokos** [comment]
I hear you. I like `week-number-of-year` myself, I'd be glad to rename this function to that.

**Comment by seancorfield** [comment]
I'd be fine with that. I'd like @michaelklishin to weigh in, in case he has any strong preference.

**Comment by michaelklishin** [comment]
I find `week-number-of-year` to be precise enough.

**Comment by adomokos** [comment]
Closing. See the new function name in [PR 167](https://github.com/clj-time/clj-time/pull/167).

**Pull request closed without merging**
